routes/web.php
<?php

use App\Http\Controllers\CourseController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\MainController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [MainController::class, 'index'])->name('home');

Route::group(['prefix' => 'courses', 'as' => 'courses.'], function() {
    Route::get('/', [CourseController::class, 'index'])->name('index');
    Route::post('/', [CourseController::class, 'create'])->name('create');
    Route::get('new', [CourseController::class, 'new'])->name('new');
    Route::delete('{course}', [CourseController::class, 'destroy'])->name('destroy');
    Route::get('{course}', [CourseController::class, 'show'])->name('show');
    Route::put('{course}', [CourseController::class, 'update'])->name('update');
    Route::get('{course}/edit', [CourseController::class, 'edit'])->name('edit');
});


Route::group(['prefix' => 'departments', 'as' => 'departments.'], function() {
    Route::get('/', [DepartmentController::class, 'index'])->name('index');
    Route::post('/', [DepartmentController::class, 'create'])->name('create');
    Route::get('new', [DepartmentController::class, 'new'])->name('new');
    Route::get('{department}/edit', [DepartmentController::class, 'edit'])->name('edit');
    Route::get('{department}', [DepartmentController::class, 'show'])->name('show');
    Route::put('{department}', [DepartmentController::class, 'update'])->name('update');
    Route::delete('{department}', [DepartmentController::class, 'destroy'])->name('destroy');
});

app/Models/Course.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    use HasFactory;

    protected $table = 'courses';

    protected $fillable = ['name', 'ects','code','description', 'department_id'];


    public function department() {

        return $this->belongsTo(Department::Class);
    }
}

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Department extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'code',
        'description'
    ];

    public function courses() {
        return $this->hasMany(Course::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CourseController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Course;
use App\Models\Department;


class CourseController extends Controller
{
    public function index()
    {

        $courses = Course::all();

        return view('courses.index', ['courses' => $courses]);
    }

    public function show(Course $course)
    {
        return view('courses.show', ['course' => $course]);
    }

    public function new()
    {
        $departments = Department::all();
        return view('courses.create', ['departments' => $departments]);
    }

    public function create()
    {
        request()->validate([
            'name'          => 'required',
            'ects'          => 'required',
            'code'          => 'required',
            'description'   => 'required',
            'department_id' => 'required'
        ]);

        $course = Course::create([
            'name'          => request('name'),
            'ects'          => request('ects'),
            'code'          => request('code'),
            'description'   => request('description'),
            'department_id' => request('department_id')
        ]);

        return redirect()->route('courses.index')->with('message', "Course $course->name created successfully");
    }

    public function edit(Course $course)
    {
        $departments = Department::all();

        return view('courses.edit', ['course' => $course, 'departments' => $departments]);

    }

    public function update(Course $course)
    {
        request()->validate([
            'name'          => 'required',
            'code'          => 'required',
            'description'   => 'required',
            'department_id' => 'required'
        ]);

        $course->update([
            'name'          => request('name'),
            'code'          => request('code'),
            'description'   => request('description'),
            'ects'          => request('ects'),
            'department_id' => request('department_id')
        ]);

        return redirect('/courses')->with('message', "Course $course->name updated successfully");
    }

    public function destroy(Course $course)
    {
        $course->delete();

        return redirect()->route('courses.index')->with('message', "Course $course->name deleted successfully");
    }
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Department;
use App\Models\Course;
use Illuminate\Http\Request;


class DepartmentController extends Controller
{
    public function index()
    {

        $departments = Department::all();

        return view('departments.index', ['departments' => $departments]);
    }

    public function show(Department $department)
    {
        return view('departments.show', ['department' => $department]);
    }

    public function edit(Department $department)
    {

        return view('departments.edit', ['department' => $department]);

    }

    public function new()
    {

        return view('departments.create');
    }

    public function create()
    {
        request()->validate([
            'name'        => 'required',
            'code'        => 'required',
            'description' => 'required'
        ]);

        $department = Department::create([
            'name'        => request('name'),
            'code'        => request('code'),
            'description' => request('description')
        ]);

        return redirect()->route('departments.index')->with('message', "Department $department->code created successfully");
    }

    public function update(Department $department)
    {

        request()->validate([
            'name'        => 'required',
            'code'        => 'required',
            'description' => 'required'
        ]);

        $department->update([
            'name'        => request('name'),
            'code'        => request('code'),
            'description' => request('description')

        ]);

        return redirect()->route('departments.show', $department->id)->with('message', "Department $department->code updated successfully");
    }

    public function destroy(Department $department)
    {

        $department->delete();

        return redirect()->route('departments.index');
    }
}

app/Http/Controllers/MainController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MainController extends Controller
{
    public function index(){
        return view('main');
    }
}

resources/views/courses/create.blade.php
@extends('master')

@section('content')
    <div style="width: 800px;" class="container max-w-full mx-auto pt-4">
        <form action="{{ route('courses.create') }}" method="POST">
            @csrf
            <div class="bg-gray-200">
                <div class="container h-screen flex justify-center items-center">
                    <div class="relative">
                        <h2 class="text-xl font-bold text-gray-90">Create course</h2>
                        <div class="p-4 top-4 center-3">
                            <label for="name"> Course name:</label><br>
                            <input type="text"
                                   class="h-14 w-96 pl-10 pr-20 rounded-lg z-0 focus:shadow focus:outline-none"
                                   placeholder="Enter name..." name="name" id="name">
                        </div>
                        <div class="p-4 top-4 center-3">
                            <label for="name"> ECTS-value:</label><br>
                            <input type="text"
                                   class="h-14 w-96 pl-10 pr-20 rounded-lg z-0 focus:shadow focus:outline-none"
                                   placeholder="Enter ECTS..." name="ects" id="ects">
                        </div>
                        <div class="p-4 top-4 center-3">
                            <label for="code">Course code:</label><br>
                            <input type="text"
                                   class="h-14 w-96 pl-10 pr-20 rounded-lg z-0 focus:shadow focus:outline-none"
                                   placeholder="Enter code..." name="code" id="code">
                        </div>
                        <div class="p-4 top-4 center-3">
                            <label for="description"> Course description:</label><br>
                            <input type="text"
                                   class="h-14 w-96 pl-10 pr-20 rounded-lg z-0 focus:shadow focus:outline-none"
                                   placeholder="Enter description..." name="description" id="description">
                        </div>


                        <div class="p-4 top-4 center-3">
                            <label for="department_id">Department: </label>
                            <select style="background-color:white;"
                                    class="form-select h-14 w-96 block mt-1 rounded-lg pl-10 pr-20" name="department_id"
                                    id="department_id">
                                @foreach($departments as $department)
                                    <option value="{{ $department->id }}">{{ $department->name }}</option>
                                @endforeach
                            </select>
                            <input class="mt-4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
                                   type="submit"/>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/courses/edit.blade.php
@extends('master')

@section('content')
    <div style="width: 800px;" class="container max-w-full mx-auto pt-4">
        <div>
            <div class="bg-gray-200">
                <div class="container h-screen flex justify-center items-center flex-column">
                    <form class="relative" action="/courses/{{ $course->id }}" method="POST">
                        @method('PUT')
                        @csrf
                        <h2 class="text-xl font-bold text-gray-90">Edit course</h2>
                        <div class="p-4 top-4 center-3">
                            <label for="name"> Course name:</label><br>
                            <input type="text"
                                   class="h-14 w-96 pl-10 pr-20 rounded-lg z-0 focus:shadow focus:outline-none"
                                   placeholder="Enter name..." name="name" value="{{ $course->name }}" id="name">
                        </div>
                        <div class="p-4 top-4 center-3">
                            <label for="name"> ECTS-value:</label><br>
                            <input type="text"
                                   class="h-14 w-96 pl-10 pr-20 rounded-lg z-0 focus:shadow focus:outline-none"
                                   placeholder="Enter ECTS..." name="ects" value="{{ $course->ects }} " id="ects">
                        </div>
                        <div class="p-4 top-4 center-3">
                            <label for="code">Course code:</label><br>
                            <input type="text"
                                   class="h-14 w-96 pl-10 pr-20 rounded-lg z-0 focus:shadow focus:outline-none"
                                   placeholder="Enter code..." name="code" value="{{ $course->code }}" id="code">
                        </div>
                        <div class="p-4 top-4 center-3">
                            <label for="description"> Course description:</label><br>
                            <input type="text"
                                   class="h-14 w-96 pl-10 pr-20 rounded-lg z-0 focus:shadow focus:outline-none"
                                   placeholder="Enter description..." name="description"
                                   value="{{ $course->description }} " id="description">
                        </div>


                        <div class="p-4 top-4 center-3">
                            <label for="department_id">Department: </label>
                            <select style="background-color:white;"
                                    class="form-select h-14 w-96 block mt-1 rounded-lg pl-10 pr-20" name="department_id"
                                    id="department_id">
                                @foreach($departments as $department)
                                <option value="{{ $department->id }}" @if($department->id == $course->department_id) selected @endif>{{ $department->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <br>


                        <input class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
                               type="submit"/>

                        <a href="{{ route('courses.index') }}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Cancel</a>
                    </form>

                    <form action="{{ route('courses.destroy', $course->id) }}" method="post" class="w-100">
                        @csrf
                        @method('DELETE')
                        <button class="ml-20 bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/courses/index.blade.php
@extends('master')

@section('content')
    <div style="width: 800px;" class="container max-w-full mx-auto pt-4">
        @if(session()->has('message'))
        <div class="alert alert-success success-message" role="alert">
            {{ session('message') }}
        </div>
        @endif
        <h2 class="text-xl font-bold text-gray-90">All courses</h2>
        <table class="table">
            <tr>
                <th style="text-align: left;">Name</th>
                <th>ECTS-value</th>
                <th>Code</th>
                <th>Description</th>
                <th>Department</th>
                <th>Actions</th>
            </tr>
            @foreach($courses as $course)
                <tr>
                    <td><a class="text-blue-500" href="{{ route('courses.show', $course->id) }}">{{ $course->name  }}</td>
                    <td>{{ $course->ects }}</td>
                    <td>{{ $course->code }}</td>
                    <td>{{ $course->description }}</td>
                    <td>{{ $course->department->name }} </td>
                    <td><a class="text-blue-500" href="{{ route('courses.edit', $course->id) }}">Edit</a></td>
                <tr>
            @endforeach
        </table>
        <a href="{{ route('courses.new') }}">
            <button class="mt-6 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" type="button">
                Create New
            </button>
        </a>
    </div>
@endsection

resources/views/courses/show.blade.php
@extends('master')

@section('content')
    <div style="width: 800px;" class="container max-w-full mx-auto pt-4">
        <div class=" bg-gray-200">
            <div class="container h-screen flex justify-center items-center">
                <div class="relative">
                    <h2 class="text-xl font-bold text-gray-90">Show course</h2>
                    <div class="p-2 top-2 center-2"><p class="h-14 w-96  pr-20 ">Name: {{ $course->name }}</p> </div>
                    <div class="p-2 top-2 center-2"><p class="h-14 w-96  pr-20 ">Code: {{ $course->code }}</p> </div>
                    <div class="p-2 top-2 center-2"><p class="h-14 w-96  pr-20 ">ECTS-value: {{ $course->ects }}</p> </div>
                    <div class="p-2 top-2 center-2"><p class="h-14 w-96  pr-20 ">Description: {{ $course->description }} </p>  </div>
                    <div class="p-2 top-2 center-2"><p class="h-14 w-96  pr-20 ">Department: {{ $course->department->name }} </p> </div>
                    <div class="p-2  top-4 center-3">
                        <a href="{{ route('courses.index') }}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Go back</a>
                    </div>
                </div>

            </div>

        </div>
    </div>
@endsection

resources/views/departments/create.blade.php
@extends('master')

@section('content')
    <div class="container mx-auto pt-4">
        <form action="{{ route('departments.create') }}" method="POST">
            @csrf

            <div class=" bg-gray-200">
                <div class="py-8 flex justify-center items-center">
                    <div class="relative">
                        <h2 class="text-xl font-bold text-gray-90">Create department</h2>
                        <div class="p-4 top-4 center-3"><i
                                class="fa fa-search text-gray-400 z-20 hover:text-gray-500"></i></div>
                        <input type="text" class="h-14 w-96 pl-10 pr-20 rounded-lg z-0 shadow-sm focus:shadow focus:outline-none"
                               placeholder="Enter name..." name="name" id="name">
                        <div class="p-4 top-4 center-3"><i
                                class="fa fa-search text-gray-400 z-20 hover:text-gray-500"></i></div>
                        <input type="text" class="h-14 w-96 pl-10 pr-20 rounded-lg z-0  shadow-sm focus:shadow focus:outline-none"
                               placeholder="Enter code..." name="code" id="code">
                        <div class="p-4 top-4 center-3"><i
                                class="fa fa-search text-gray-400 z-20 hover:text-gray-500"></i></div>
                        <input type="text" class="h-14 w-96 pl-10 pr-20 rounded-lg z-0  shadow-sm focus:shadow focus:outline-none"
                               placeholder="Enter description..." name="description" id="description">
                        <div class="pt-8 top-4 center-3">
                            <input class="submit bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
                                   type="submit" value="Create"/>


                            <a href="{{ route('departments.index') }}"
                               class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Cancel</a>

                        </div>
                    </div>

                </div>

            </div>


        </form>
    </div>
@endsection

resources/views/departments/edit.blade.php
@extends('master')

@section('content')
    <div>
        <div class=" bg-gray-200">
            <div class="container flex justify-center items-center flex-column pt-4">
                <form  action="{{ route('departments.show', $department->id) }}" method="POST" class="relative">
                    @method('PUT')
                    @csrf
                    <h2 class="text-xl font-bold text-gray-90">Edit department</h2>
                    <div class="p-4 top-4 center-3"><i class="fa fa-search text-gray-400 z-20 hover:text-gray-500"></i>
                    </div>
                    <input type="text" class="h-14 w-96 pl-10 pr-20 rounded-lg z-0 focus:shadow focus:outline-none"
                           placeholder="Enter name..." name="name" value="{{ $department->name }}" id="name">
                    <div class="p-4 top-4 center-3"><i class="fa fa-search text-gray-400 z-20 hover:text-gray-500"></i>
                    </div>
                    <input type="text" class="h-14 w-96 pl-10 pr-20 rounded-lg z-0 focus:shadow focus:outline-none"
                           placeholder="Enter code..." name="code" value="{{ $department->code }}" id="code">
                    <div class="p-4 top-4 center-3"><i class="fa fa-search text-gray-400 z-20 hover:text-gray-500"></i>
                    </div>
                    <input type="text" class="h-14 w-96 pl-10 pr-20 rounded-lg z-0 focus:shadow focus:outline-none"
                           placeholder="Enter description..." name="description" value="{{ $department->description }}"
                           id="description">
                    <div class="top-4 center-3 mt-4">
                        <input class="submit bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
                               type="submit" value="Save"/>
                        <a href="{{ route('departments.index') }}"
                           class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Cancel</a>
                    </div>
                </form>

                <form action="{{ route('departments.destroy', $department->id) }}" method='post' class="w-100">
                    @csrf
                    @method('delete')
                    <button class="ml-4 bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Delete</button>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/departments/index.blade.php
@extends('master')

@section('content')
    <div style="width: 800px;" class="container max-w-full mx-auto pt-4 bg-grey-200">
        <h2 class="text-xl font-bold text-gray-90">All departments</h2>
        @if(session()->has('message'))
            <div class="alert alert-success success-message" role="alert">
                {{ session('message') }}
            </div>
        @endif
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Code</th>
                <th>Description</th>
                <th></th>
            </tr>
            @foreach($departments as $department)
                <tr class="department">
                    <td><a class="text-blue-500" href="/departments/{{ $department->id }}">{{ $department->name  }}</td>
                    <td>{{ $department->code }}</td>
                    <td style="width: 240px">{{ $department->description}}</td>
                    <td><a class="text-blue-500 edit" href="/departments/{{ $department->id }}/edit">Edit</a></td>
                <tr>
            @endforeach
        </table>

        <a href="{{ route('departments.new') }}"
           class="new mt-6 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            Create New
        </a>
    </div>
@endsection

resources/views/departments/show.blade.php
@extends('master')

@section('content')
    <div style="width: 800px;" class="container max-w-full mx-auto pt-4">
        @if(session()->has('message'))
            <div class="alert alert-success success-message" role="alert">
                {{ session('message') }}
            </div>
        @endif
        <div class="bg-gray-200">
            <div class="container h-screen flex justify-center items-center">
                <div class="relative">
                    <h2 class="text-xl font-bold text-gray-90">Show department</h2>
                    <div class="p-2 top-2 center-2"><p class="h-14 w-96  pr-20 ">Name: {{ $department->name }}</p></div>
                    <div class="p-2 top-2 center-2"><p class="h-14 w-96  pr-20 ">Code: {{ $department->code }}</p></div>
                    <div class="p-2 top-2 center-2"><p class="h-14 w-96  pr-20 ">
                            Description: {{ $department->description }} </p></div>
                    <div class="p-2 top-2 center-2"><p class="h-14 w-96  pr-20 "> Courses:
                        <ul>
                            @foreach($department->courses as $course)
                                <li> {{ $course->name }}
                            @endforeach
                        </ul>
                    </div>

                    <div class="p-2  top-4 center-3">
                        <a href="{{ route('departments.index') }}"
                           class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Go back</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/main.blade.php
@extends('master')

@section('content')
    <div class="container main">
        <p>Welcome to WebTech ItsLearning</p>
        <h3 class="display-3"> Main </h3>
        <a href="{{ route('departments.index') }}" class="departments-link">Departments</a><br>
        <a href="{{ route('courses.index') }}" class="courses-link">Courses</a>
        {{ \Illuminate\Support\Facades\DB::connection()->getDatabaseName() }}
    </div>
@endsection

resources/views/master.blade.php
<html>
<head>
    <title>Assignment 1</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{{ route('home') }}">WebTech E21</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{{ route('departments.index') }}">Departments</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('courses.index') }}">Courses</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
@yield('content')
</body>
</html>